"use strict";

const PUZZLES = [
	{
		"type":"5x5",
		puzzles: [
			{"rows":5,"cols":5,"elems":[{"x":0,"y":0,"type":"dot","color_index":"4"},{"x":2,"y":0,"type":"dot","color_index":"1"},{"x":4,"y":0,"type":"dot","color_index":"2"},{"x":2,"y":1,"type":"dot","color_index":"0"},{"x":4,"y":1,"type":"dot","color_index":"3"},{"x":1,"y":3,"type":"dot","color_index":"1"},{"x":3,"y":3,"type":"dot","color_index":"2"},{"x":1,"y":4,"type":"dot","color_index":"4"},{"x":2,"y":4,"type":"dot","color_index":"0"},{"x":3,"y":4,"type":"dot","color_index":"3"}]},
			{"rows":5,"cols":5,"elems":[{"x":0,"y":0,"type":"dot","color_index":"2"},{"x":2,"y":2,"type":"dot","color_index":"1"},{"x":0,"y":3,"type":"dot","color_index":"0"},{"x":1,"y":3,"type":"dot","color_index":"1"},{"x":2,"y":3,"type":"dot","color_index":"4"},{"x":4,"y":3,"type":"dot","color_index":"2"},{"x":0,"y":4,"type":"dot","color_index":"4"},{"x":4,"y":4,"type":"dot","color_index":"0"}]},
			{"rows":5,"cols":5,"elems":[{"x":1,"y":0,"type":"dot","color_index":"2"},{"x":2,"y":0,"type":"dot","color_index":"0"},{"x":3,"y":0,"type":"dot","color_index":"1"},{"x":3,"y":1,"type":"dot","color_index":"4"},{"x":2,"y":2,"type":"dot","color_index":"4"},{"x":0,"y":3,"type":"dot","color_index":"2"},{"x":3,"y":3,"type":"dot","color_index":"3"},{"x":0,"y":4,"type":"dot","color_index":"0"},{"x":2,"y":4,"type":"dot","color_index":"3"},{"x":3,"y":4,"type":"dot","color_index":"1"}]},
			{"rows":5,"cols":5,"elems":[{"x":3,"y":0,"type":"dot","color_index":"4"},{"x":4,"y":0,"type":"dot","color_index":"1"},{"x":0,"y":1,"type":"dot","color_index":"4"},{"x":2,"y":2,"type":"dot","color_index":"2"},{"x":3,"y":3,"type":"dot","color_index":"0"},{"x":0,"y":4,"type":"dot","color_index":"1"},{"x":1,"y":4,"type":"dot","color_index":"0"},{"x":2,"y":4,"type":"dot","color_index":"2"}]},
			{"rows":5,"cols":5,"elems":[{"x":3,"y":0,"type":"dot","color_index":"4"},{"x":4,"y":0,"type":"dot","color_index":"1"},{"x":1,"y":1,"type":"dot","color_index":"2"},{"x":2,"y":1,"type":"dot","color_index":"0"},{"x":3,"y":1,"type":"dot","color_index":"1"},{"x":4,"y":3,"type":"dot","color_index":"0"},{"x":2,"y":4,"type":"dot","color_index":"4"},{"x":4,"y":4,"type":"dot","color_index":"2"}]},
			{"rows":5,"cols":5,"elems":[{"x":0,"y":0,"type":"dot","color_index":"2"},{"x":2,"y":0,"type":"dot","color_index":"0"},{"x":3,"y":0,"type":"dot","color_index":"4"},{"x":4,"y":0,"type":"dot","color_index":"1"},{"x":3,"y":2,"type":"dot","color_index":"1"},{"x":1,"y":3,"type":"dot","color_index":"0"},{"x":4,"y":3,"type":"dot","color_index":"4"},{"x":4,"y":4,"type":"dot","color_index":"2"}]},
			{"rows":5,"cols":5,"elems":[{"x":0,"y":0,"type":"dot","color_index":"0"},{"x":3,"y":0,"type":"dot","color_index":"2"},{"x":0,"y":1,"type":"dot","color_index":"1"},{"x":0,"y":2,"type":"dot","color_index":"2"},{"x":2,"y":2,"type":"dot","color_index":"1"},{"x":3,"y":2,"type":"dot","color_index":"0"},{"x":1,"y":3,"type":"dot","color_index":"4"},{"x":3,"y":3,"type":"dot","color_index":"4"}]},
			{"rows":5,"cols":5,"elems":[{"x":0,"y":0,"type":"dot","color_index":"0"},{"x":3,"y":0,"type":"dot","color_index":"4"},{"x":4,"y":0,"type":"dot","color_index":"3"},{"x":3,"y":1,"type":"dot","color_index":"2"},{"x":2,"y":2,"type":"dot","color_index":"2"},{"x":1,"y":3,"type":"dot","color_index":"4"},{"x":2,"y":3,"type":"dot","color_index":"3"},{"x":4,"y":3,"type":"dot","color_index":"1"},{"x":1,"y":4,"type":"dot","color_index":"0"},{"x":2,"y":4,"type":"dot","color_index":"1"}]},
			{"rows":5,"cols":5,"elems":[{"x":3,"y":0,"type":"dot","color_index":"4"},{"x":1,"y":1,"type":"dot","color_index":"2"},{"x":2,"y":1,"type":"dot","color_index":"0"},{"x":3,"y":1,"type":"dot","color_index":"1"},{"x":2,"y":2,"type":"dot","color_index":"2"},{"x":0,"y":4,"type":"dot","color_index":"0"},{"x":1,"y":4,"type":"dot","color_index":"1"},{"x":2,"y":4,"type":"dot","color_index":"4"}]},
			{"rows":5,"cols":5,"elems":[{"x":0,"y":1,"type":"dot","color_index":"1"},{"x":3,"y":1,"type":"dot","color_index":"4"},{"x":0,"y":2,"type":"dot","color_index":"0"},{"x":1,"y":2,"type":"dot","color_index":"4"},{"x":2,"y":2,"type":"dot","color_index":"0"},{"x":3,"y":2,"type":"dot","color_index":"2"},{"x":0,"y":4,"type":"dot","color_index":"2"},{"x":4,"y":4,"type":"dot","color_index":"1"}]},						
		]
	},
	{
		"type":"6x6",
		puzzles: [
			{"rows":6,"cols":6,"elems":[{"x":0,"y":0,"type":"dot","color_index":"1"},{"x":1,"y":0,"type":"dot","color_index":"2"},{"x":2,"y":0,"type":"dot","color_index":"5"},{"x":4,"y":0,"type":"dot","color_index":"4"},{"x":5,"y":0,"type":"dot","color_index":"0"},{"x":4,"y":1,"type":"dot","color_index":"3"},{"x":2,"y":2,"type":"dot","color_index":"5"},{"x":2,"y":3,"type":"dot","color_index":"4"},{"x":0,"y":4,"type":"dot","color_index":"1"},{"x":2,"y":4,"type":"dot","color_index":"3"},{"x":0,"y":5,"type":"dot","color_index":"2"},{"x":2,"y":5,"type":"dot","color_index":"0"}]},
			{"rows":6,"cols":6,"elems":[{"x":1,"y":0,"type":"dot","color_index":"3"},{"x":2,"y":0,"type":"dot","color_index":"0"},{"x":5,"y":0,"type":"dot","color_index":"1"},{"x":2,"y":2,"type":"dot","color_index":"2"},{"x":3,"y":2,"type":"dot","color_index":"4"},{"x":5,"y":2,"type":"dot","color_index":"1"},{"x":3,"y":3,"type":"dot","color_index":"5"},{"x":5,"y":3,"type":"dot","color_index":"0"},{"x":1,"y":4,"type":"dot","color_index":"4"},{"x":2,"y":4,"type":"dot","color_index":"2"},{"x":4,"y":4,"type":"dot","color_index":"5"},{"x":5,"y":4,"type":"dot","color_index":"3"}]},
			{"rows":6,"cols":6,"elems":[{"x":1,"y":1,"type":"dot","color_index":"2"},{"x":4,"y":1,"type":"dot","color_index":"1"},{"x":3,"y":2,"type":"dot","color_index":"4"},{"x":2,"y":4,"type":"dot","color_index":"2"},{"x":3,"y":4,"type":"dot","color_index":"0"},{"x":4,"y":4,"type":"dot","color_index":"1"},{"x":2,"y":5,"type":"dot","color_index":"0"},{"x":3,"y":5,"type":"dot","color_index":"4"}]},
			{"rows":6,"cols":6,"elems":[{"x":0,"y":0,"type":"dot","color_index":"2"},{"x":0,"y":3,"type":"dot","color_index":"4"},{"x":1,"y":3,"type":"dot","color_index":"1"},{"x":2,"y":3,"type":"dot","color_index":"0"},{"x":3,"y":3,"type":"dot","color_index":"1"},{"x":0,"y":4,"type":"dot","color_index":"2"},{"x":1,"y":4,"type":"dot","color_index":"0"},{"x":3,"y":4,"type":"dot","color_index":"4"}]},
			{"rows":6,"cols":6,"elems":[{"x":0,"y":0,"type":"dot","color_index":"1"},{"x":0,"y":2,"type":"dot","color_index":"2"},{"x":3,"y":2,"type":"dot","color_index":"4"},{"x":4,"y":2,"type":"dot","color_index":"2"},{"x":4,"y":3,"type":"dot","color_index":"0"},{"x":1,"y":4,"type":"dot","color_index":"0"},{"x":4,"y":4,"type":"dot","color_index":"4"},{"x":4,"y":5,"type":"dot","color_index":"1"}]},
			{"rows":6,"cols":6,"elems":[{"x":3,"y":0,"type":"dot","color_index":"4"},{"x":5,"y":0,"type":"dot","color_index":"1"},{"x":1,"y":1,"type":"dot","color_index":"3"},{"x":3,"y":1,"type":"dot","color_index":"2"},{"x":4,"y":2,"type":"dot","color_index":"4"},{"x":5,"y":2,"type":"dot","color_index":"1"},{"x":2,"y":3,"type":"dot","color_index":"0"},{"x":3,"y":3,"type":"dot","color_index":"2"},{"x":4,"y":3,"type":"dot","color_index":"5"},{"x":5,"y":3,"type":"dot","color_index":"3"},{"x":2,"y":4,"type":"dot","color_index":"5"},{"x":0,"y":5,"type":"dot","color_index":"0"}]},
			{"rows":6,"cols":6,"elems":[{"x":2,"y":0,"type":"dot","color_index":"0"},{"x":3,"y":0,"type":"dot","color_index":"2"},{"x":1,"y":1,"type":"dot","color_index":"3"},{"x":2,"y":1,"type":"dot","color_index":"1"},{"x":5,"y":1,"type":"dot","color_index":"2"},{"x":3,"y":2,"type":"dot","color_index":"0"},{"x":5,"y":2,"type":"dot","color_index":"4"},{"x":2,"y":3,"type":"dot","color_index":"3"},{"x":0,"y":4,"type":"dot","color_index":"4"},{"x":4,"y":4,"type":"dot","color_index":"1"}]},
			{"rows":6,"cols":6,"elems":[{"x":4,"y":0,"type":"dot","color_index":"0"},{"x":5,"y":0,"type":"dot","color_index":"1"},{"x":2,"y":1,"type":"dot","color_index":"4"},{"x":2,"y":2,"type":"dot","color_index":"3"},{"x":2,"y":3,"type":"dot","color_index":"2"},{"x":3,"y":3,"type":"dot","color_index":"1"},{"x":1,"y":4,"type":"dot","color_index":"4"},{"x":4,"y":4,"type":"dot","color_index":"0"},{"x":1,"y":5,"type":"dot","color_index":"3"},{"x":2,"y":5,"type":"dot","color_index":"2"}]},
			{"rows":6,"cols":6,"elems":[{"x":0,"y":0,"type":"dot","color_index":"4"},{"x":1,"y":0,"type":"dot","color_index":"1"},{"x":5,"y":0,"type":"dot","color_index":"1"},{"x":2,"y":1,"type":"dot","color_index":"5"},{"x":5,"y":1,"type":"dot","color_index":"5"},{"x":0,"y":2,"type":"dot","color_index":"3"},{"x":5,"y":2,"type":"dot","color_index":"4"},{"x":1,"y":3,"type":"dot","color_index":"2"},{"x":5,"y":3,"type":"dot","color_index":"2"},{"x":1,"y":4,"type":"dot","color_index":"0"},{"x":5,"y":4,"type":"dot","color_index":"0"},{"x":5,"y":5,"type":"dot","color_index":"3"}]},
			{"rows":6,"cols":6,"elems":[{"x":0,"y":0,"type":"dot","color_index":"4"},{"x":3,"y":1,"type":"dot","color_index":"3"},{"x":4,"y":1,"type":"dot","color_index":"0"},{"x":5,"y":1,"type":"dot","color_index":"4"},{"x":3,"y":2,"type":"dot","color_index":"2"},{"x":5,"y":2,"type":"dot","color_index":"1"},{"x":2,"y":3,"type":"dot","color_index":"1"},{"x":1,"y":4,"type":"dot","color_index":"2"},{"x":2,"y":4,"type":"dot","color_index":"3"},{"x":4,"y":4,"type":"dot","color_index":"0"}]},						
		]
	},
	{
		"type":"7x7",
		puzzles: [
			{"rows":7,"cols":7,"elems":[{"x":6,"y":0,"type":"dot","color_index":"0"},{"x":5,"y":1,"type":"dot","color_index":"3"},{"x":6,"y":1,"type":"dot","color_index":"4"},{"x":1,"y":2,"type":"dot","color_index":"3"},{"x":3,"y":3,"type":"dot","color_index":"1"},{"x":4,"y":3,"type":"dot","color_index":"5"},{"x":2,"y":4,"type":"dot","color_index":"1"},{"x":4,"y":4,"type":"dot","color_index":"2"},{"x":4,"y":5,"type":"dot","color_index":"4"},{"x":5,"y":5,"type":"dot","color_index":"2"},{"x":5,"y":6,"type":"dot","color_index":"0"},{"x":6,"y":6,"type":"dot","color_index":"5"}]},
			{"rows":7,"cols":7,"elems":[{"x":1,"y":0,"type":"dot","color_index":"6"},{"x":2,"y":0,"type":"dot","color_index":"4"},{"x":2,"y":1,"type":"dot","color_index":"3"},{"x":3,"y":1,"type":"dot","color_index":"0"},{"x":5,"y":1,"type":"dot","color_index":"0"},{"x":2,"y":2,"type":"dot","color_index":"1"},{"x":2,"y":3,"type":"dot","color_index":"5"},{"x":3,"y":3,"type":"dot","color_index":"2"},{"x":5,"y":3,"type":"dot","color_index":"1"},{"x":4,"y":4,"type":"dot","color_index":"2"},{"x":5,"y":4,"type":"dot","color_index":"5"},{"x":2,"y":5,"type":"dot","color_index":"3"},{"x":2,"y":6,"type":"dot","color_index":"6"},{"x":3,"y":6,"type":"dot","color_index":"4"}]},
			{"rows":7,"cols":7,"elems":[{"x":0,"y":0,"type":"dot","color_index":"5"},{"x":0,"y":1,"type":"dot","color_index":"2"},{"x":6,"y":1,"type":"dot","color_index":"5"},{"x":0,"y":2,"type":"dot","color_index":"6"},{"x":2,"y":2,"type":"dot","color_index":"6"},{"x":3,"y":2,"type":"dot","color_index":"3"},{"x":4,"y":2,"type":"dot","color_index":"1"},{"x":6,"y":2,"type":"dot","color_index":"2"},{"x":0,"y":3,"type":"dot","color_index":"8"},{"x":2,"y":3,"type":"dot","color_index":"4"},{"x":6,"y":3,"type":"dot","color_index":"1"},{"x":0,"y":4,"type":"dot","color_index":"0"},{"x":5,"y":4,"type":"dot","color_index":"3"},{"x":6,"y":4,"type":"dot","color_index":"4"},{"x":1,"y":5,"type":"dot","color_index":"8"},{"x":6,"y":6,"type":"dot","color_index":"0"}]},
			{"rows":7,"cols":7,"elems":[{"x":0,"y":1,"type":"dot","color_index":"1"},{"x":2,"y":2,"type":"dot","color_index":"2"},{"x":4,"y":3,"type":"dot","color_index":"2"},{"x":2,"y":4,"type":"dot","color_index":"3"},{"x":4,"y":4,"type":"dot","color_index":"0"},{"x":0,"y":5,"type":"dot","color_index":"4"},{"x":1,"y":5,"type":"dot","color_index":"0"},{"x":4,"y":5,"type":"dot","color_index":"3"},{"x":5,"y":5,"type":"dot","color_index":"4"},{"x":0,"y":6,"type":"dot","color_index":"1"}]},
			{"rows":7,"cols":7,"elems":[{"x":0,"y":0,"type":"dot","color_index":"5"},{"x":1,"y":0,"type":"dot","color_index":"0"},{"x":2,"y":0,"type":"dot","color_index":"2"},{"x":5,"y":1,"type":"dot","color_index":"1"},{"x":1,"y":2,"type":"dot","color_index":"4"},{"x":3,"y":2,"type":"dot","color_index":"2"},{"x":1,"y":3,"type":"dot","color_index":"3"},{"x":4,"y":3,"type":"dot","color_index":"0"},{"x":2,"y":4,"type":"dot","color_index":"4"},{"x":4,"y":4,"type":"dot","color_index":"1"},{"x":1,"y":6,"type":"dot","color_index":"5"},{"x":6,"y":6,"type":"dot","color_index":"3"}]},
			{"rows":7,"cols":7,"elems":[{"x":0,"y":1,"type":"dot","color_index":"5"},{"x":1,"y":1,"type":"dot","color_index":"4"},{"x":3,"y":1,"type":"dot","color_index":"4"},{"x":5,"y":1,"type":"dot","color_index":"1"},{"x":2,"y":2,"type":"dot","color_index":"6"},{"x":3,"y":2,"type":"dot","color_index":"5"},{"x":4,"y":2,"type":"dot","color_index":"1"},{"x":2,"y":3,"type":"dot","color_index":"2"},{"x":6,"y":3,"type":"dot","color_index":"0"},{"x":2,"y":4,"type":"dot","color_index":"3"},{"x":4,"y":5,"type":"dot","color_index":"2"},{"x":6,"y":5,"type":"dot","color_index":"0"},{"x":4,"y":6,"type":"dot","color_index":"6"},{"x":6,"y":6,"type":"dot","color_index":"3"}]},
			{"rows":7,"cols":7,"elems":[{"x":0,"y":1,"type":"dot","color_index":"1"},{"x":1,"y":1,"type":"dot","color_index":"4"},{"x":5,"y":1,"type":"dot","color_index":"4"},{"x":0,"y":2,"type":"dot","color_index":"3"},{"x":1,"y":2,"type":"dot","color_index":"1"},{"x":1,"y":3,"type":"dot","color_index":"0"},{"x":3,"y":3,"type":"dot","color_index":"0"},{"x":1,"y":4,"type":"dot","color_index":"2"},{"x":2,"y":4,"type":"dot","color_index":"3"},{"x":5,"y":4,"type":"dot","color_index":"2"}]},
			{"rows":7,"cols":7,"elems":[{"x":4,"y":0,"type":"dot","color_index":"1"},{"x":6,"y":0,"type":"dot","color_index":"5"},{"x":1,"y":1,"type":"dot","color_index":"5"},{"x":6,"y":1,"type":"dot","color_index":"3"},{"x":2,"y":3,"type":"dot","color_index":"2"},{"x":3,"y":3,"type":"dot","color_index":"4"},{"x":6,"y":3,"type":"dot","color_index":"4"},{"x":3,"y":4,"type":"dot","color_index":"0"},{"x":6,"y":4,"type":"dot","color_index":"0"},{"x":1,"y":5,"type":"dot","color_index":"3"},{"x":2,"y":5,"type":"dot","color_index":"2"},{"x":3,"y":5,"type":"dot","color_index":"6"},{"x":5,"y":6,"type":"dot","color_index":"1"},{"x":6,"y":6,"type":"dot","color_index":"6"}]},
			{"rows":7,"cols":7,"elems":[{"x":5,"y":0,"type":"dot","color_index":"3"},{"x":6,"y":0,"type":"dot","color_index":"4"},{"x":0,"y":1,"type":"dot","color_index":"3"},{"x":1,"y":1,"type":"dot","color_index":"5"},{"x":2,"y":1,"type":"dot","color_index":"1"},{"x":4,"y":2,"type":"dot","color_index":"0"},{"x":6,"y":2,"type":"dot","color_index":"0"},{"x":1,"y":3,"type":"dot","color_index":"2"},{"x":6,"y":3,"type":"dot","color_index":"4"},{"x":5,"y":4,"type":"dot","color_index":"1"},{"x":6,"y":4,"type":"dot","color_index":"5"},{"x":5,"y":5,"type":"dot","color_index":"2"}]},
			{"rows":7,"cols":7,"elems":[{"x":1,"y":0,"type":"dot","color_index":"5"},{"x":1,"y":1,"type":"dot","color_index":"3"},{"x":4,"y":2,"type":"dot","color_index":"0"},{"x":3,"y":3,"type":"dot","color_index":"4"},{"x":3,"y":4,"type":"dot","color_index":"2"},{"x":2,"y":5,"type":"dot","color_index":"1"},{"x":5,"y":5,"type":"dot","color_index":"4"},{"x":0,"y":6,"type":"dot","color_index":"5"},{"x":2,"y":6,"type":"dot","color_index":"3"},{"x":3,"y":6,"type":"dot","color_index":"2"},{"x":4,"y":6,"type":"dot","color_index":"0"},{"x":5,"y":6,"type":"dot","color_index":"1"}]},								
		]
	},
	{
		"type":"8x8",
		puzzles: [
			{"rows":8,"cols":8,"elems":[{"x":4,"y":0,"type":"dot","color_index":"4"},{"x":4,"y":1,"type":"dot","color_index":"5"},{"x":6,"y":1,"type":"dot","color_index":"1"},{"x":7,"y":1,"type":"dot","color_index":"2"},{"x":4,"y":2,"type":"dot","color_index":"1"},{"x":5,"y":2,"type":"dot","color_index":"2"},{"x":7,"y":2,"type":"dot","color_index":"5"},{"x":3,"y":3,"type":"dot","color_index":"3"},{"x":4,"y":3,"type":"dot","color_index":"0"},{"x":4,"y":4,"type":"dot","color_index":"3"},{"x":4,"y":5,"type":"dot","color_index":"0"},{"x":1,"y":7,"type":"dot","color_index":"4"}]},
		]
	},
	{
		"type":"9x9",
		puzzles: [
			{"rows":9,"cols":9,"elems":[{"x":1,"y":1,"type":"dot","color_index":"4"},{"x":2,"y":1,"type":"dot","color_index":"5"},{"x":3,"y":1,"type":"dot","color_index":"0"},{"x":3,"y":2,"type":"dot","color_index":"5"},{"x":4,"y":2,"type":"dot","color_index":"3"},{"x":6,"y":2,"type":"dot","color_index":"3"},{"x":7,"y":2,"type":"dot","color_index":"0"},{"x":7,"y":3,"type":"dot","color_index":"6"},{"x":1,"y":4,"type":"dot","color_index":"1"},{"x":3,"y":4,"type":"dot","color_index":"1"},{"x":4,"y":4,"type":"dot","color_index":"4"},{"x":0,"y":5,"type":"dot","color_index":"2"},{"x":1,"y":5,"type":"dot","color_index":"6"},{"x":7,"y":5,"type":"dot","color_index":"8"},{"x":8,"y":5,"type":"dot","color_index":"7"},{"x":1,"y":6,"type":"dot","color_index":"7"},{"x":2,"y":6,"type":"dot","color_index":"2"},{"x":1,"y":7,"type":"dot","color_index":"8"}]},
		]
	},
	{
		"type":"Rohan",
		puzzles: [	
			{"rows":5,"cols":5,"elems":[{"x":0,"y":0,"type":"dot","color_index":"4"},{"x":2,"y":0,"type":"dot","color_index":"0"},{"x":4,"y":0,"type":"dot","color_index":"2"},{"x":0,"y":1,"type":"dot","color_index":"3"},{"x":1,"y":2,"type":"dot","color_index":"3"},{"x":2,"y":2,"type":"dot","color_index":"4"},{"x":0,"y":3,"type":"dot","color_index":"0"},{"x":0,"y":4,"type":"dot","color_index":"5"},{"x":3,"y":4,"type":"dot","color_index":"5"},{"x":4,"y":4,"type":"dot","color_index":"2"}]},
			{"rows":14,"cols":14,"elems":[{"x":0,"y":0,"type":"dot","color_index":"4"},{"x":1,"y":0,"type":"dot","color_index":"1"},{"x":6,"y":0,"type":"dot","color_index":"5"},{"x":7,"y":0,"type":"dot","color_index":"3"},{"x":7,"y":1,"type":"dot","color_index":"0"},{"x":6,"y":6,"type":"dot","color_index":"0"},{"x":7,"y":6,"type":"dot","color_index":"3"},{"x":8,"y":6,"type":"dot","color_index":"5"},{"x":11,"y":13,"type":"dot","color_index":"4"},{"x":12,"y":13,"type":"dot","color_index":"1"}]},
			{"rows":3,"cols":3,"elems":[{"x":0,"y":0,"type":"dot","color_index":"0"},{"x":2,"y":0,"type":"dot","color_index":"4"},{"x":1,"y":1,"type":"dot","color_index":"4"},{"x":2,"y":1,"type":"dot","color_index":"0"}]},
			{"rows":5,"cols":5,"elems":[{"x":0,"y":0,"type":"dot","color_index":"4"},{"x":4,"y":0,"type":"dot","color_index":"4"}]},
		]
	}
];